### PR TITLE
Add vercel.json basic auth example

### LINKED ISSUE #24: Simple basic auth for SPA's using `vercel.json`
It seems like you might be able to add basic auth to a simple SPA using `vercel.json` like so:

https://github.com/orgs/vercel/discussions/2920

### PR DESCRIPTION
**Pull request by ubergarm**
Closes #24

### CODE REVIEW

**Comment by flawyte** [comment]
Thanks a lot for the PR! :+1: 

I've cloned your branch, made a few changes to be able to run the repo's unit tests against your new example and tested both on my local machine & when [deployed](https://vercel-basic-auth-vercel-json.vercel.app/)... but it doesn't work.

When testing manually I noticed that you can't get past the basic auth prompt, it keeps asking for credentials forever, even when they are valid.

To check by yourself, I've added testing instructions in the repo's root README. Everything is on the new `add-example-vercel-json` branch in this repo.

**Comment by ubergarm** [comment]
Note that the vercel cli tool will throw a warning that "has" and "missing"
don't work locally iirc.

i'm using basically this on a production app so the concept is sound , must
be a detail i didn't test in this exact version...

But yes i see your deployed example — perhaps it is the basic auth base64
encoded string ... for some reason what i have has extra [padding
characters](
https://stackoverflow.com/questions/6916805/why-does-a-base64-encoded-string-have-an-sign-at-the-end)
the [example here](
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic_authentication)
does not...

So possibly it is "working" but the username combo i randomly picked is not
encoded to the correct base64 string i committed without testing ...

If you can try the base64 string from the mozilla link example perhaps that
will allow you through. I may have time to look into it more later this
weekend if you have no luck.

You can also open your browser dev tools and look at the request in the
networking tab to see exactly what token your browser is sending which must
match the exact value in the `vercel.json`.

Thanks!

**Comment by ubergarm** [comment]
I'm back at the keyboard and looked a bit more closely at your deployment. I see you are using username/password of `admin/admin` in your updated example now.

While my browser also keeps throwing up the dialogue box too, I tested using `httpie` (a nice python CLI tool like `curl`) and it seems to be working:

```bash
$ http GET https://vercel-basic-auth-vercel-json.vercel.app/admin Authorization:"Basic YWRtaW46YWRtaW4K"

HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 5
Cache-Control: public, max-age=0, must-revalidate
Connection: keep-alive
Content-Disposition: inline; filename="admin"
Content-Length: 435
Content-Type: text/html; charset=utf-8
Date: Tue, 18 Jul 2023 14:35:55 GMT
Etag: "d9a0696061a2480b041c9e078252c60b"
Server: Vercel
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Vercel-Cache: HIT
X-Vercel-Id: iad1::xr57x-1689690955397-6ead8bb52061

<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <link href='/_styles/app.css' rel='stylesheet'>
  <link href='/admin/_styles/admin.css' rel='stylesheet'>
  <script src='/admin/index.js'></script>
</head>
<body>

  <h1><img src='/admin/_assets/ic_dashboard.svg'> Dashboard <span class='admin-area'>(admin area)</span></h1>
  <a href='/admin/users.html'>Users &#8594;</a><br />
  <a href='/'>&#8592; Home</a>

</body>
</html>
```

As I'm not sure what else you changed in your deployed version over the PR I submitted I'm not sure why it keeps sending the browser back to the dialogue box.

**Comment by ubergarm** [comment]
Okie, i figured it out and pushed another commit to this PR. 

I had forgotten to use `echo -n` to not encode a `\n` character... So the base64 string had an extra character which is impossible to send from the browser.

Let me know how you want to handle this PR e.g. merge it and then you add in your changes etc.

Cheers!

**Comment by flawyte** [comment]
Thanks for the fix!

In my case, I also had the same problem (8379e11) but for the record I was also using an invalid path in the `vercel.json` file which was part of the infinite prompt loop problem (0caa161), and finally a line return at the end of my `401.html` file was preventing some unit tests from passing (d0a6937).

Now everything works perfectly! I even noticed when running the tests that the `vercel.json` method is way faster than the others :partying_face:

Thanks again!
Cheers

**Pull request merged**
